# Generated by Django 4.2 on 2025-01-30 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(choices=[('Laptop', 'Laptop'), ('Phone', 'Phone'), ('Others', 'Others')], max_length=10)),
                ('other_device_type', models.CharField(blank=True, max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('issue_description', models.TextField()),
                ('resolve_description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
